### ISSUE TITLE
Trim leading space from labels

### ISSUE THREAD

**Issue by rotscher** [postfinance/discovery#18]
Trim leading (and trailing?) spaces from labels while registering (or correctly tokenize input).

E.g. following register command has a label ("label2") which has a leading space after registering with prometheus:

```
discovery service register -e http://example.com/metrics example --labels=label1=value1, label2=value2
```

Scraping in Prometheus won't work and logs the following error:
```
Apr 20 11:11:40 foobar prometheus[536382]: level=error ts=2021-04-20T09:11:40.078Z caller=file.go:344 component="discovery manager scrape" discovery=file msg="Error reading file" path=/appl/prometheus/service-discovery/foobar/appl/MY_APP.json err="\" label2\" is not a valid label name"
```

Maybe, the same issue also applies to label values.

**Comment by zbindenren** [comment]
This is done by the upstream flag library. The correct usage is:

```console
discovery service register -e http://example.com/metrics example --labels=label1=value1,label2=value2
```

No space between `,`.

**Comment by rotscher** [comment]
Thanks for the hint for the correct usage but incorrect usage should not pretend to be correct.

Which one is the upstream flag library?

**Comment by zbindenren** [comment]
https://github.com/alecthomas/kong

**Comment by zbindenren** [comment]
Ok I see your point. I think the best way would be to fail the command when a space is detected on label key or value.

**Comment by zbindenren** [comment]
From the prometheus  [doc](https://prometheus.io/docs/concepts/data_model/):

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex `[a-zA-Z_][a-zA-Z0-9_]*.`  Label names beginning with __ are reserved for internal use.
>
> Label values may contain any Unicode characters.

I will use the regex to validate label names.
