### ISSUE TITLE
Feature: distribute endpoints based on samples count

### ISSUE THREAD

**Issue by muryoutaisuu** [postfinance/discovery#22]
example situation: 2 prometheus instances promA and promB, 4 endpoints. Endpoints A, B and C have 400 samples, while endpoint D has 3'000.

Currently, endpoints will be distributed to something like this:

promA: A + B = 800 samples
promB: C + D = 3'400 samples

ideally, endpoints will be distributed to better distribute samples instead of endpoints...

promA: A + B + C = 1'200 samples
promB: D = 3'000 samples

...or a reasonable mix thereof

**Comment by zbindenren** [comment]
This is a feature which would complicate things a lot. And with the current configuration it is not necessary anymore. So closing this one.
